// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: api/proto/replication.proto

package go_kvs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Replication_StreamReplication_FullMethodName = "/kvs.Replication/StreamReplication"
)

// ReplicationClient is the client API for Replication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicationClient interface {
	// Follower calls this to receive stream of commands from leader
	StreamReplication(ctx context.Context, in *FollowerInfo, opts ...grpc.CallOption) (Replication_StreamReplicationClient, error)
}

type replicationClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationClient(cc grpc.ClientConnInterface) ReplicationClient {
	return &replicationClient{cc}
}

func (c *replicationClient) StreamReplication(ctx context.Context, in *FollowerInfo, opts ...grpc.CallOption) (Replication_StreamReplicationClient, error) {
	stream, err := c.cc.NewStream(ctx, &Replication_ServiceDesc.Streams[0], Replication_StreamReplication_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &replicationStreamReplicationClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Replication_StreamReplicationClient interface {
	Recv() (*ReplicationCommand, error)
	grpc.ClientStream
}

type replicationStreamReplicationClient struct {
	grpc.ClientStream
}

func (x *replicationStreamReplicationClient) Recv() (*ReplicationCommand, error) {
	m := new(ReplicationCommand)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReplicationServer is the server API for Replication service.
// All implementations must embed UnimplementedReplicationServer
// for forward compatibility
type ReplicationServer interface {
	// Follower calls this to receive stream of commands from leader
	StreamReplication(*FollowerInfo, Replication_StreamReplicationServer) error
	mustEmbedUnimplementedReplicationServer()
}

// UnimplementedReplicationServer must be embedded to have forward compatible implementations.
type UnimplementedReplicationServer struct {
}

func (UnimplementedReplicationServer) StreamReplication(*FollowerInfo, Replication_StreamReplicationServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamReplication not implemented")
}
func (UnimplementedReplicationServer) mustEmbedUnimplementedReplicationServer() {}

// UnsafeReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServer will
// result in compilation errors.
type UnsafeReplicationServer interface {
	mustEmbedUnimplementedReplicationServer()
}

func RegisterReplicationServer(s grpc.ServiceRegistrar, srv ReplicationServer) {
	s.RegisterService(&Replication_ServiceDesc, srv)
}

func _Replication_StreamReplication_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FollowerInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicationServer).StreamReplication(m, &replicationStreamReplicationServer{stream})
}

type Replication_StreamReplicationServer interface {
	Send(*ReplicationCommand) error
	grpc.ServerStream
}

type replicationStreamReplicationServer struct {
	grpc.ServerStream
}

func (x *replicationStreamReplicationServer) Send(m *ReplicationCommand) error {
	return x.ServerStream.SendMsg(m)
}

// Replication_ServiceDesc is the grpc.ServiceDesc for Replication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Replication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvs.Replication",
	HandlerType: (*ReplicationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamReplication",
			Handler:       _Replication_StreamReplication_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/replication.proto",
}
