// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.3
// source: api/proto/replication.proto

package go_kvs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FollowerId   string `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowerAddr string `protobuf:"bytes,2,opt,name=follower_addr,json=followerAddr,proto3" json:"follower_addr,omitempty"`
	LastSequence int64  `protobuf:"varint,3,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"` // Last sequence follower has applied
}

func (x *FollowerInfo) Reset() {
	*x = FollowerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_replication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerInfo) ProtoMessage() {}

func (x *FollowerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_replication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerInfo.ProtoReflect.Descriptor instead.
func (*FollowerInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *FollowerInfo) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowerInfo) GetFollowerAddr() string {
	if x != nil {
		return x.FollowerAddr
	}
	return ""
}

func (x *FollowerInfo) GetLastSequence() int64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

type ReplicationCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command  []byte `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Sequence int64  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *ReplicationCommand) Reset() {
	*x = ReplicationCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_replication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationCommand) ProtoMessage() {}

func (x *ReplicationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_replication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationCommand.ProtoReflect.Descriptor instead.
func (*ReplicationCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_replication_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicationCommand) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ReplicationCommand) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_api_proto_replication_proto protoreflect.FileDescriptor

var file_api_proto_replication_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6b,
	0x76, 0x73, 0x22, 0x79, 0x0a, 0x0c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x4a, 0x0a,
	0x12, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x32, 0x52, 0x0a, 0x0b, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11, 0x2e,
	0x6b, 0x76, 0x73, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x1a, 0x17, 0x2e, 0x6b, 0x76, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x00, 0x30, 0x01, 0x42, 0x1c, 0x5a,
	0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x73, 0x61, 0x6b,
	0x69, 0x79, 0x65, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x6b, 0x76, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_proto_replication_proto_rawDescOnce sync.Once
	file_api_proto_replication_proto_rawDescData = file_api_proto_replication_proto_rawDesc
)

func file_api_proto_replication_proto_rawDescGZIP() []byte {
	file_api_proto_replication_proto_rawDescOnce.Do(func() {
		file_api_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_replication_proto_rawDescData)
	})
	return file_api_proto_replication_proto_rawDescData
}

var file_api_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_replication_proto_goTypes = []interface{}{
	(*FollowerInfo)(nil),       // 0: kvs.FollowerInfo
	(*ReplicationCommand)(nil), // 1: kvs.ReplicationCommand
}
var file_api_proto_replication_proto_depIdxs = []int32{
	0, // 0: kvs.Replication.StreamReplication:input_type -> kvs.FollowerInfo
	1, // 1: kvs.Replication.StreamReplication:output_type -> kvs.ReplicationCommand
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_replication_proto_init() }
func file_api_proto_replication_proto_init() {
	if File_api_proto_replication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_replication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_replication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicationCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_replication_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_replication_proto_goTypes,
		DependencyIndexes: file_api_proto_replication_proto_depIdxs,
		MessageInfos:      file_api_proto_replication_proto_msgTypes,
	}.Build()
	File_api_proto_replication_proto = out.File
	file_api_proto_replication_proto_rawDesc = nil
	file_api_proto_replication_proto_goTypes = nil
	file_api_proto_replication_proto_depIdxs = nil
}
